trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: Docker Hub
  - name: projectName
    value: $(System.TeamProject)
  - name: dockerRepository
    value: $(DOCKERHUB_USERNAME)/metacriticscraper
  - name: dockerImageVersionTag
    value: 0.1.$(Build.BuildId)

jobs:
  - job: BuildSolution
    displayName: Build Solution
    steps:
      - task: DotNetCoreCLI@2
        displayName: Building
        inputs:
          command: build
          arguments: --configuration $(buildConfiguration) $(projectName).sln

      - task: DotNetCoreCLI@2
        displayName: Running Unit Tests
        inputs:
          command: test
          projects: '**/*UnitTests.csproj'
          arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: Unit Tests

      - task: DotNetCoreCLI@2
        displayName: Running Integration Tests
        inputs:
          command: test
          projects: '**/*IntegrationTests.csproj'
          arguments: '--configuration $(buildConfiguration) --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: Integration Tests

  - job: PrepareDockerImage
    displayName: Build & Push Docker Image
    dependsOn: BuildSolution
    steps:
      - task: Docker@2
        displayName: Building & Publishing Docker Image
        inputs:
          repository: $(dockerRepository)
          command: buildAndPush
          Dockerfile: $(projectName)/Dockerfile
          buildContext: .
          tags: |
            latest
            $(dockerImageVersionTag)