trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-latest

variables:
  projectName: $(System.TeamProject)
  dockerRepository: $(DOCKERHUB_USERNAME)/metacriticscraper

jobs:
  - job: BuildSolution
    displayName: Build Solution
    steps:
      - task: DotNetCoreCLI@2
        displayName: Building
        inputs:
          command: build
          arguments: --configuration $(buildConfiguration) $(projectName).sln

      - task: DotNetCoreCLI@2
        displayName: Running Unit Tests
        inputs:
          command: test
          projects: '**/*UnitTests.csproj'
          arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: Run tests

      - task: DotNetCoreCLI@2
        displayName: Running Integration Tests
        inputs:
          command: test
          projects: '**/*IntegrationTests.csproj'
          arguments: '--configuration $(buildConfiguration) --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: Run tests

  - job: BuildDockerImage
    displayName: Build Docker Image
    steps:
      - task: Docker@2
        displayName: Building Docker Image
        inputs:
          repository: $(dockerRepository)
          command: build
          Dockerfile: $(projectName)/Dockerfile
          buildContext: .
  
  - job: PublishDockerImage
    displayName: Push Docker Image
    dependsOn:
      - BuildSolution
      - BuildDockerImage
    steps:
      - task: Docker@2
        displayName: Pushing Docker Image
        inputs:
          containerRegistry: DockerHub
          repository: $(dockerRepository)
          command: push
          tags: |
            latest
            0.1.$(Build.BuildId)