trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: $(System.TeamProject)

jobs:
  - job: Build
    displayName: Build Solution
    steps:
      - script: dotnet build --configuration $(buildConfiguration) $(projectName).sln
        displayName: 'Building'

  - job: Test
    displayName: Execute Tests
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/*Tests/*.csproj'
          arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --settings $(System.DefaultWorkingDirectory)/.runsettings'
          testRunTitle: 'Run tests'
        displayName: 'Running Unit & Integration Tests'