trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: Docker Hub
  - name: projectName
    value: $(System.TeamProject)
  - name: dockerRepository
    value: $(DOCKERHUB_USERNAME)/metacriticscraper
  - name: dockerImageVersion
    value: 0.1.$(Build.BuildId)
  - name: dockerImageArtifactName
    value: docker-image.tar

jobs:
  - job: BuildSolution
    displayName: Build Solution
    steps:
      - task: DotNetCoreCLI@2
        displayName: Building
        inputs:
          command: build
          arguments: --configuration $(buildConfiguration) $(projectName).sln

      - task: DotNetCoreCLI@2
        displayName: Running Unit Tests
        inputs:
          command: test
          projects: '**/*UnitTests.csproj'
          arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: Run tests

      - task: DotNetCoreCLI@2
        displayName: Running Integration Tests
        inputs:
          command: test
          projects: '**/*IntegrationTests.csproj'
          arguments: '--configuration $(buildConfiguration) --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: Run tests

  - job: BuildDockerImage
    displayName: Build Docker Image
    steps:
      - task: Docker@2
        name: dockerBuild
        displayName: Building Docker Image
        inputs:
          repository: $(dockerRepository)
          command: build
          Dockerfile: $(projectName)/Dockerfile
          buildContext: .
          tags: |
            latest
            $(dockerImageVersion)

      - task: Docker@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          action: 'Run a Docker command'
          customCommand: 'image save $(dockerRepository):$(dockerImageVersion) -o $(Build.ArtifactStagingDirectory)/$(dockerImageArtifactName)'

      - task: PublishBuildArtifacts@1
        displayName: Publishing Docker Image
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)/$(dockerImageArtifactName)
          ArtifactName: $(dockerImageArtifactName)
  
  - job: PublishDockerImage
    displayName: Push Docker Image
    dependsOn:
      - BuildSolution
      - BuildDockerImage
    steps:
      - task: DownloadBuildArtifacts@1
        displayName: Downloading Docker Image
        inputs:
          artifactName: $(dockerImageArtifactName)
          downloadPath: $(Pipeline.Workspace)

      - task: Docker@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          action: 'Run a Docker command'
          customCommand: 'image load -i $(Pipeline.Workspace)/$(dockerImageArtifactName)'

      - task: Docker@2
        displayName: Pushing Docker Image
        inputs:
          containerRegistry: DockerHub
          repository: $(dockerRepository)
          command: push
          tags: |
            latest
            $(dockerImageVersion)