trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: $(System.TeamProject)

jobs:
  - job: Build
    displayName: Build Solution
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration) $(projectName).sln'
        displayName: 'Building'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/*UnitTests.csproj'
          arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: 'Run tests'
        displayName: 'Running Unit Tests'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/*IntegrationTests.csproj'
          arguments: '--configuration $(buildConfiguration) --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: 'Run tests'
        displayName: 'Running Integration Tests'