trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: Docker Hub
  - name: projectName
    value: $(System.TeamProject)
  - name: dockerRepository
    value: $(DOCKERHUB_USERNAME)/metacriticscraper

jobs:
  - job: BuildSolution
    displayName: Build Solution
    steps:
      - task: DotNetCoreCLI@2
        displayName: Building
        inputs:
          command: build
          arguments: --configuration $(buildConfiguration) $(projectName).sln

      - task: DotNetCoreCLI@2
        displayName: Running Unit Tests
        inputs:
          command: test
          projects: '**/*UnitTests.csproj'
          arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: Run tests

      - task: DotNetCoreCLI@2
        displayName: Running Integration Tests
        inputs:
          command: test
          projects: '**/*IntegrationTests.csproj'
          arguments: '--configuration $(buildConfiguration) --settings $(System.DefaultWorkingDirectory)/.runsettings --no-build'
          testRunTitle: Run tests

  - job: BuildDockerImage
    displayName: Build Docker Image
    steps:
      - task: Docker@2
        displayName: Building Docker Image
        inputs:
          repository: $(dockerRepository)
          command: build
          Dockerfile: $(projectName)/Dockerfile
          buildContext: .
          tags: |
            latest
            0.1.$(Build.BuildId)

      - task: PublishBuildArtifacts@1
        displayName: Publishing Docker Image
        inputs:
          PathtoPublish: $(BuildDockerImage.DockerOutput)
          ArtifactName: 'docker-image'
  
  - job: PublishDockerImage
    displayName: Push Docker Image
    dependsOn:
      - BuildSolution
      - BuildDockerImage
    steps:
      - task: DownloadBuildArtifacts@1
        displayName: Downloading Docker Image
        inputs:
          artifactName: 'docker-image'
          downloadPath: $[ dependencies.BuildDockerImage.outputs['BuildDockerImage.DockerOutput'] ]

      - task: Docker@2
        displayName: Pushing Docker Image
        inputs:
          containerRegistry: DockerHub
          repository: $(dockerRepository)
          command: push
          tags: |
            latest
            0.1.$(Build.BuildId)